swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /globaltemperature:
    get:
      operationId: "globaltemperature.read"
      tags:
        - "Global Temperature"
      summary: "The temperature data structure supported by the server application"
      description: "Read the list of temperature"
      responses:
        200:
          description: "Successful read temperature list operation"
          schema:
            type: "array"
            items:
              properties:
                reading_time:
                  type: "string"
                devicename:
                  type: "string"
                humidity:
                  type: "number"
                temp:
                  type: "number"
                moved:
                  type: "number"
                label:
                  type: "number"
                
    put:
      operationId: "globaltemperature.create"
      tags:
        - Global Temperature
      summary: Create a temperature record and add it to the people list
      description: Create a new temperature in the database
      parameters:
        - name: globaltemperature
          in: body
          description: Temperature record to create
          required: True
          schema:
            type: object
            properties:
              reading_time:
                type: "string"
              devicename:
                type: "string"
              humidity:
                type: "number"
              temp:
                type: "number"
              moved:
                type: "number"
              label:
                type: "number"
      responses:
        200:
          description: Successfully created temperature record in database
  /predictlabel:
    get:
      operationId: "predictlabel.predict"
      tags:
        - Predict label
      summary: "Predict whether it would using the temperature and humidity passed in from node"
      description: "Predict whether it would using the temperature and humidity passed in from node"
      parameters:
        - name: temp
          in: query
          description: Temperature
          required: true
          type: number
        - name: humidity
          in: query
          description: Temperature
          required: true
          type: number
        - name: moved
          in: query
          description: Moved
          required: true
          type: number
        
      responses:
        200:
          description: "Successful prediction"          