swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /data:
    get:
      operationId: "dht11_move.read"
      tags:
        - "Data"
      summary: "The data structure supported by the server application"
      description: "Read the list of data"
      responses:
        200:
          description: "Successful read data list operation"
          schema:
            type: "array"
            items:
              properties:
                # id:
                #   type: "number"
                reading_time:
                  type: "string"
                devicename:
                  type: "string"
                humidity:
                  type: "number"
                temperature:
                  type: "number"
                moved:
                  type: "boolean"